#!/usr/bin/env python3
"""Extract the javadoc description of every Baritone setting from Settings.java.

Generates:
  - src/main/resources/baritone_settings_docs.json  (shipped in the jar; read by the AI's
    settings tools on demand so the docs never bloat the model context)
  - docs/SETTINGS.md                                (human-readable reference)

Re-run this script whenever settings are added or their javadocs change:
  python3 scripts/extract_settings_docs.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_JAVA = os.path.join(ROOT, "src/api/java/baritone/api/Settings.java")
JSON_OUT = os.path.join(ROOT, "src/main/resources/baritone_settings_docs.json")
MD_OUT = os.path.join(ROOT, "docs/SETTINGS.md")

DECL_RE = re.compile(r"public\s+final\s+Setting<.*?>\s+(\w+)\s*=")


def clean_javadoc(block_lines):
    """Turn raw javadoc lines into plain readable text."""
    text_lines = []
    for line in block_lines:
        line = line.strip()
        line = re.sub(r"^/\*\*", "", line)
        line = re.sub(r"\*/$", "", line)
        line = re.sub(r"^\*\s?", "", line)
        if line.startswith("@see") or line.startswith("@apiNote") or line.startswith("@deprecated"):
            continue
        text_lines.append(line)
    text = " ".join(text_lines)
    # javadoc inline tags -> plain text
    text = re.sub(r"\{@(?:code|link|linkplain|literal|value)\s+([^}]*)\}", r"\1", text)
    # html
    text = re.sub(r"<p\s*/?>", " ", text)
    text = re.sub(r"<br\s*/?>", " ", text)
    text = re.sub(r"</?(?:b|i|em|strong|tt|ul|li|ol|a)[^>]*>", "", text)
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def main():
    with open(SETTINGS_JAVA, encoding="utf-8") as f:
        lines = f.readlines()

    docs = {}
    order = []
    javadoc = None      # lines of the most recent javadoc block
    in_javadoc = False
    current_block = []

    for raw in lines:
        stripped = raw.strip()
        if not in_javadoc and stripped.startswith("/**"):
            current_block = [stripped]
            if "*/" in stripped:
                javadoc = current_block
                current_block = []
            else:
                in_javadoc = True
            continue
        if in_javadoc:
            current_block.append(stripped)
            if "*/" in stripped:
                javadoc = current_block
                current_block = []
                in_javadoc = False
            continue
        m = DECL_RE.search(raw)
        if m:
            name = m.group(1)
            desc = clean_javadoc(javadoc) if javadoc else ""
            docs[name] = desc
            order.append(name)
            javadoc = None
            continue
        # any other significant code line between a javadoc and a declaration that is not an
        # annotation/blank invalidates the javadoc pairing
        if stripped and not stripped.startswith("@") and not stripped.startswith("//"):
            javadoc = None

    if len(docs) < 200:
        print(f"ERROR: only extracted {len(docs)} settings, expected 200+; parser broken?", file=sys.stderr)
        sys.exit(1)

    empty = [n for n in order if not docs[n]]

    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(docs, f, indent=1, ensure_ascii=False)
        f.write("\n")

    os.makedirs(os.path.dirname(MD_OUT), exist_ok=True)
    with open(MD_OUT, "w", encoding="utf-8") as f:
        f.write("# Baritone settings reference\n\n")
        f.write("Auto-generated by `scripts/extract_settings_docs.py` from the javadocs in "
                "`src/api/java/baritone/api/Settings.java`. Do not edit by hand.\n\n")
        f.write(f"{len(order)} settings.\n\n")
        for name in order:
            f.write(f"### {name}\n\n")
            f.write((docs[name] or "(no description)") + "\n\n")

    print(f"Extracted {len(order)} settings -> {os.path.relpath(JSON_OUT, ROOT)}, {os.path.relpath(MD_OUT, ROOT)}")
    if empty:
        print(f"note: {len(empty)} settings have no javadoc: {', '.join(empty[:10])}"
              + (" ..." if len(empty) > 10 else ""))


if __name__ == "__main__":
    main()
